- platform: unifigateway
  host: 10.0.0.6
  username: !secret unifi_username
  password: !secret unifi_password
  monitored_conditions:
    - www
    - wlan
    - alerts
    - firmware

# - platform: miflora
#   mac: 'C4:7C:8D:62:73:AC'
#   name: Peace Lily
#   monitored_conditions:
#     - moisture
#     - temperature
#     - light
#     - conductivity
#     - battery

# - platform: miflora
#   mac: 'C4:7C:8D:62:6C:D2'
#   name: Dracaena
#   monitored_conditions:
#     - moisture
#     - temperature
#     - light
#     - conductivity
#     - battery

- platform: thermal_comfort
  sensors:
    basement:
      friendly_name: Basement
      temperature_sensor: sensor.basement_temperature
      humidity_sensor: sensor.basement_humidity
    inside:
      friendly_name: Inside
      temperature_sensor: sensor.thermostat_temperature
      humidity_sensor: sensor.thermostat_humidity
    outside:
      friendly_name: Outside
      temperature_sensor: sensor.outside_temperature
      humidity_sensor: sensor.outside_humidity
    dht22:
      friendly_name: DHT22
      temperature_sensor: sensor.dht22_temperature
      humidity_sensor: sensor.dht22_humidity

- platform: template
  sensors:
    # From https://community.home-assistant.io/t/first-alert-z-wave-smoke-carbon-monoxide-detectors-dont-show-up-in-home-assistant/1332/15
    basement_smoke_alarm_state:
      value_template: >-
        {%- if is_state("sensor.basement_smoke_alarm_alarm_level", "0") -%}
          Clear
        {%- elif is_state("sensor.basement_smoke_alarm_alarm_type", "1") -%}
          Fire
        {%- elif is_state("sensor.basement_smoke_alarm_alarm_type", "2") -%}
          CO
        {%- elif is_state("sensor.basement_smoke_alarm_alarm_type", "12") -%}
          Testing
        {%- elif is_state("sensor.basement_smoke_alarm_alarm_type", "13") -%}
          Clear
        {% else -%}
          Unknown
        {%- endif -%}
      friendly_name: 'Basement Smoke Alarm'
      icon_template: hass:smoke-detector

- platform: history_stats
  name: Maple Sprinkler Runtime Today
  entity_id: switch.maple_sprinkler
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Apple and Lemon Sprinkler Runtime Today
  entity_id: switch.apple_and_lemon_sprinkler
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Vegetable Box Sprinkler Runtime Today
  entity_id: switch.vegetable_box_sprinkler
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Lime Tree Sprinkler Runtime Today
  entity_id: switch.lime_tree_sprinkler
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Curb Sprinkler Runtime Today
  entity_id: switch.curb_sprinkler
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Orange Tree Sprinkler Runtime Today
  entity_id: switch.orange_tree_sprinkler
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: filter
  name: "Filtered TVOC"
  entity_id: sensor.ccs811_total_volatile_organic_compound
  filters:
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:05"
        precision: 0

- platform: history_stats
  name: TV on Today
  entity_id: media_player.55_tcl_roku_tv
  state:
    - "on"
    - "playing"
  type: time
  start: "{{ now().replace(hour=4, minute=0, second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: Sump Activated Count
  entity_id: binary_sensor.sump_pump
  type: count
  state:
    - "on"
  start: "{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: Sump Pump Runtime This Week
  entity_id: binary_sensor.sump_pump
  type: time
  state: 'on'
  # Since Monday morning at midnight
  start: "{{ as_timestamp( now().replace(hour=0, minute=0, second=0, microsecond=0) ) - now().weekday() * 86400 }}"
  end: "{{ now() }}"
