esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

packages:
  common: !include common.yaml

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    id: side_button
    name: "Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    id: power
    current:
      name: "Current"
      accuracy_decimals: 1
      filters:
        - or:
          - throttle: 60s
          - delta: 0.1
    voltage:
      name: "Input Voltage"
      accuracy_decimals: 1
      filters:
        - or:
          - throttle: 60s
          - delta: 5.0
    power:
      name: "Power Consumption"
      device_class: power
      unit_of_measurement: "W"
      accuracy_decimals: 1
      id: cse_power
      filters:
        - or:
          - throttle: 60s
          - delta: 5.0
    energy:
      name: "Energy"
      accuracy_decimals: 2
      filters:
        - throttle: 60s
    apparent_power:
      name: "Apparent Power"
      filters:
        - throttle_average: 60s
    power_factor:
      name: "Power Factor"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
  - platform: total_daily_energy
    name: "Daily Energy"
    power_id: cse_power
    accuracy_decimals: 2

switch:
  - platform: gpio
    id: relay    
    pin: GPIO12
    name: "Power"

time:
  - platform: sntp
    id: common_time

status_led:
  pin:
    number: GPIO13
    inverted: True
