esphome:
  name: air-sensor
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air Sensor Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_encryption_key
  services:
    - service: mhz19_calibrate_zero
      then:
        - mhz19.calibrate_zero: mhz19_sensor

ota:

uart:
  - id: "mhz19_uart"
    tx_pin: 17
    rx_pin: 16
    baud_rate: 9600
  - id: "pms5003_uart"
    tx_pin: 18
    rx_pin: 5
    baud_rate: 9600

i2c:
  sda: 21
  scl: 22

sensor:
  - platform: mhz19
    id: mhz19_sensor
    co2:
      name: "MH-Z19 CO2 Value"
      filters:
        - sliding_window_moving_average:
            window_size: 24
            send_every: 6
    temperature:
      name: "MH-Z19 Temperature"
      filters:
        - sliding_window_moving_average:
            window_size: 24
            send_every: 6
    update_interval: 10s
    automatic_baseline_calibration: true
    uart_id: "mhz19_uart"
  - platform: pmsx003
    type: PMSX003
    uart_id: "pms5003_uart"
    pm_1_0:
      name: "PM <1.0µm µg/m³"
      filters:
        - throttle_average: 60s
    pm_2_5:
      name: "PM <2.5µm µg/m³"
      filters:
        - throttle_average: 60s
    pm_10_0:
      name: "PM <10.0µm µg/m³"
      filters:
        - throttle_average: 60s
  - platform: dht
    model: DHT22
    pin: 19
    temperature:
      name: "DHT22 Temperature"
      filters:
        - throttle_average: 60s
    humidity:
      name: "DHT22 Humidity"
      filters:
        - throttle_average: 60s
    update_interval: 5s
  - platform: ccs811
    eco2:
      name: "CCS811 eCO2 Value"
      filters:
        - throttle_average: 60s
    tvoc:
      name: "CCS811 Total Volatile Organic Compound"
      filters:
        - throttle_average: 60s
    address: 0x5A
    update_interval: 5s
    baseline: 0x2FC2
  - platform: adc
    pin: 34
    id: no2
    name: "NO2"
    attenuation: 11db
    update_interval: 5s
    filters:
      - throttle_average: 60s
      # - lambda: return 0.05f + ((10-0.05)/(2.2-0.2444444)) * (x - 0.2444444f);