substitutions:
  name: basement-atom-echo
  friendly_name: basement-atom-echo

packages:
  m5stack-atom-echo: github://esphome/firmware/wake-word-voice-assistant/m5stack-atom-echo.adopted.yaml@main
  common: !include common/common.yaml

ota:
  - id: !remove ota_esphome

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
