esphome:
  name: basement-fan
  platform: ESP8266
  board: d1_mini

packages:
  common: !include common/common.yaml

output:
  - platform: gpio
    pin: D1
    id: gpio_d1

fan:
  - platform: binary
    output: gpio_d1
    name: "Basement Fan"
