esphome:
  name: basement-fan
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Basement Fan Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

# Enable logging
logger:

ota:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_encryption_key

output:
  - platform: gpio
    pin: D1
    id: gpio_d1

fan:
  - platform: binary
    output: gpio_d1
    name: "Basement Fan"
