esphome:
  name: garage-door
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Door Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    internal: true
    pin: 3
    id: garage_door_relay

binary_sensor:
- id: garage_door_sensor
  internal: true
  platform: gpio
  pin:
    number: 1
    mode: INPUT_PULLUP
    inverted: False
  device_class: garage_door
  filters:
    - delayed_on_off: 20ms

cover:
  - platform: template
    name: "Garage Door"
    lambda: |-
      if (id(garage_door_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: garage_door_relay
      - delay: 1s
      - switch.turn_off: garage_door_relay
    close_action:
      - switch.turn_on: garage_door_relay
      - delay: 1s
      - switch.turn_off: garage_door_relay
    stop_action:
      - switch.turn_on: garage_door_relay
      - delay: 1s
      - switch.turn_off: garage_door_relay
