esphome:
  name: glowforge-power
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Glowforge Power Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_encryption_key

ota:

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Glowforge Sonoff Button"
    on_press:
      - switch.toggle: relay

sensor:
  - platform: cse7766
    current:
      name: "Glowforge Current"
      accuracy_decimals: 1
      filters:
        - or:
          - throttle: 60s
          - delta: 0.1
    voltage:
      name: "Glowforge Input Voltage"
      accuracy_decimals: 1
      filters:
        - or:
          - throttle: 60s
          - delta: 5.0
    power:
      name: "Glowforge Power Consuption"
      accuracy_decimals: 1
      filters:
        - or:
          - throttle: 60s
          - delta: 5.0
    update_interval: 1s

switch:
  - platform: gpio
    name: "Glowforge Power"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: True
