esphome:
  name: izzy-fan
  friendly_name: Izzy's Fan
  platform: ESP8266
  board: esp01_1m

packages:
  common: !include common/common.yaml

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Izzy's Fan Button"
    on_press:
      - switch.toggle: relay

sensor:
  - platform: cse7766
    current:
      name: "Izzy's Fan Current"
      accuracy_decimals: 1
      filters:
        - or:
          - throttle: 60s
          - delta: 0.1
    voltage:
      name: "Izzy's Fan Input Voltage"
      accuracy_decimals: 1
      filters:
        - or:
          - throttle: 60s
          - delta: 5.0
    power:
      name: "Izzy's Fan Power Consumption"
      accuracy_decimals: 1
      filters:
        - or:
          - throttle: 60s
          - delta: 5.0

switch:
  - platform: gpio
    name: "Izzy's Fan"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: True
