esphome:
  name: sprinkler
  on_boot:
    priority: -100
    # Send a push notification on reboot in case something went wonky when running sprinkers
    then:
      - delay: 30s
      - homeassistant.service:
          service: notify.all_devices
          data:
            message: "Sprinkler controller rebooted."
      - homeassistant.service:
          service: persistent_notification.create
          data:
            message: "Sprinkler controller rebooted. If this was expected, disregard."
            title: "Sprinkler restart"

esp8266:
  board: d1_mini_lite

packages:
  common: !include common/common.yaml

switch:
  - platform: gpio
    pin:
      number: D0
      inverted: yes
    name: "Maple Sprinkler"
    icon: "mdi:sprinkler-variant"
  - platform: gpio
    pin:
      number: D5
      inverted: yes
    name: "Apple and Lemon Sprinkler"
    icon: "mdi:sprinkler-variant"
  - platform: gpio
    pin:
      number: D2
      inverted: yes
    name: "Vegetable Box Sprinkler"
    icon: "mdi:sprinkler-variant"
  - platform: gpio
    pin:
      number: D1
      inverted: yes
    name: "Lime Tree Sprinkler"
    icon: "mdi:sprinkler-variant"
  - platform: gpio
    pin:
      number: D7
      inverted: yes
    name: "Curb Sprinkler"
    icon: "mdi:sprinkler-variant"
  - platform: gpio
    pin:
      number: D6
      inverted: yes
    name: "Orange Tree Sprinkler"
    icon: "mdi:sprinkler-variant"

sensor:
  # Uptime sensor.
  - platform: uptime
    name: Sprinkler Controller Uptime
