esphome:
  name: sump_watcher
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Enable logging
logger:
  logs:
    ct_clamp: INFO
    sensor: INFO

ota:

# Enable Home Assistant API
api:

sensor:
  - platform: ct_clamp
    internal: true
    sensor: adc_sensor
    name: "Measured Current"
    id: "sump_current"
    update_interval: 1s
    filters:
      - calibrate_linear:
        - 0 -> 0
        # Based on my Bonavita 1000w kettle
        - 0.2 -> 8.33333333
  - platform: adc
    internal: true
    pin: A0
    id: adc_sensor

binary_sensor:
  - platform: template
    name: "Sump Pump"
    lambda: |-
      if (id(sump_current).state > 2) {
        return true;
      } else {
        return false;
      }
